# When a task that used to pass starts to fail
# Go through all versions that may have been skipped to detect
# when the task started failing
stepback: true

# Mark a failure as a system/bootstrap failure (purple box) rather then a task
# failure by default.
# Actual testing tasks are marked with `type: test`
command_type: system

# Protect ourself against rogue test case, or curl gone wild, that runs forever
# 12 minutes is the longest we'll ever run
exec_timeout_secs: 3600 # 12 minutes is the longest we'll ever run

# What to do when evergreen hits the timeout (`post:` tasks are run automatically)
timeout:
- command: shell.exec
  params:
    script: |
      ls -la

functions:
  "fetch source":
    - command: git.get_project
      params:
        directory: src
    - command: shell.exec
      params:
        working_dir: "src"
        script: |
          export PROJECT_DIRECTORY="$(pwd)"

          cat <<EOT > expansion.yml
          PREPARE_SHELL: |
            set -o errexit
            set -o xtrace
            export PROJECT_DIRECTORY="$PROJECT_DIRECTORY"
          EOT
          cat expansion.yml
    - command: expansions.update
      params:
        file: src/expansion.yml

  "install dependencies":
    - command: shell.exec
      params:
        working_dir: "src"
        script: |
          ${PREPARE_SHELL}
          .evergreen/install-dependencies.sh

  "compile only":
    - command: shell.exec
      params:
        working_dir: "src"
        script: |
          ${PREPARE_SHELL}
          .evergreen/compile-only.sh

  "run tests":
    - command: shell.exec
      params:
        working_dir: "src"
        script: |
          ${PREPARE_SHELL}
          .evergreen/run-tests.sh

tasks:
- name: "compile-only"
  commands:
    - func: "fetch source"
    - func: "install dependencies"
    - func: "compile only"

- name: "test"
  depends_on:
  - name: "compile-only"
  commands:
    - func: "run tests"

buildvariants:
- name: ubuntu
  display_name: Ubuntu
  run_on:
  - ubuntu1804-test
  tasks:
  - name: "compile-only"
  - name: "test"